version: "3.9"

services:
  db:
    image: postgres
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=beeinfo
      - POSTGRES_USER=beeinfo_user
      - POSTGRES_PASSWORD=p8NJLyw4e7dLJpg4
  web:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db