# Generated by Django 3.1.3 on 2020-12-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Вопрос или ответ оператора')),
                ('slug', models.CharField(blank=True, max_length=24, null=True, verbose_name='Короткое название')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('answer_chain', models.ManyToManyField(blank=True, to='questions.Answer', verbose_name='Связка ответов')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Тема')),
                ('answers', models.ManyToManyField(blank=True, to='questions.Answer', verbose_name='Связать с другими ответами:')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
    ]
